version: '3.9'
services:

  laravel:
    build: .
    restart: unless-stopped
    ports:
      - 80:80
    command: >
      sh -c "composer install --ignore-platform-reqs --optimize-autoloader --no-interaction --no-progress && 
      /etc/service/docker-entrypoint.sh"
    volumes:
      - ./laravel:/var/www/html

  mariadb:
    image: mariadb:10.10.2
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb:/var/lib/mysql
  
volumes:
  mariadb: